[versions]
junit-jupiter = "5.10.3"
assertj = "3.11.1"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[bundles]
testlibs = ["junit-jupiter", "assertj"]
