[versions]
junit-jupiter = "5.10.3"
assertj = "3.11.1"
pitest = "1.15.0"
matlabcontrol = "5.0.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
matlabcontrol = { module = "org.n52.matlab:matlab-control", version.ref = "matlabcontrol" }

[bundles]
testlibs = ["junit-jupiter", "assertj"]

[plugins]
pitest = { id = "info.solidsoft.pitest", version.ref = "pitest" }
jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.10" }
